volumes:
    database:
        driver: local

services:
    postgres:
        image: postgres
        restart: unless-stopped
        container_name: turborepo_postgres
        shm_size: 128mb
        ports:
            - "5435:5432"
        environment:
            POSTGRES_USER: turborepo
            POSTGRES_PASSWORD: 123456789
        volumes:
            - database:/var/lib/postgresql/data
